blueprint:
  name: Climate temperature adjustment depending on temperature sensor (Fahrenheit)
  description: >
    Sets target temperature depending on second temperature sensor.
    This blueprint is inspired by this blueprint https://community.home-assistant.io/t/tado-set-offset-using-separate-temperature-sensor/288515
    created by Sanderma and Fahrenheit version https://gist.github.com/nevesenin/b875af76de99a287ff3834b988edcd4c 
    This blueprint turns on the thermostat device when temperature in one of the rooms too low.
  domain: automation
  input:
    temperature_sensor:
      name: Temperature sensor
      description: This sensor will be used as the source.
      selector:
        entity:
          domain: sensor
          device_class: temperature
    thermostat:
      name: Thermostat
      description: The thermostat to set target temperature
      selector:
        entity:
          domain: climate
    target_temperature:
      name: Target temperature
      description: The target temperature goal based on the sensor
      selector:
        number:
          min: 60
          max: 80
          step: 1
          unit_of_measurement: "°F"
      default: 67
    target_temperature_diff:
      name: Target temperature diff
      description: The diff of the target temperature of thermostat and the room (thermostat target + diff)
      selector:
        number:
          min: -5
          max: 5
          step: 1
          unit_of_measurement: "°F"
      default: 0
          
variables:
  thermostat: !input thermostat
  temperature_sensor: !input temperature_sensor
  target_temperature: !input target_temperature
  target_temperature_diff: !input target_temperature_diff
  actual_temperature: "{{ states(temperature_sensor) | float }}"
  thermostat_setpoint: "{{ state_attr(thermostat, 'temperature') }}"
  thermostat_current: "{{ state_attr(thermostat, 'current_temperature') }}"
  activate_temp: "{{ thermostat_current + 3 }}"
  deactivate_temp: "{{ thermostat_current - 3 }}"
  calculated_adjustment: "{{ actual_temperature - target_temperature_diff }}"
  calculated_target_temperature_diff: "{{ ( calculated_adjustment - thermostat_setpoint ) | round }}"

trigger:
  #- platform: state
  #  entity_id: !input thermostat
  #  attribute: "{{ current_temperature_attribute }}"
- platform: state
  entity_id: !input temperature_sensor
  
    #condition: "{{ calculated_target_temperature_diff > 0 }}"

action:
- service: system_log.write
  data:
    message: >
      {{ thermostat }} has temp set to {{ thermostat_setpoint }} F (target temp: {{ target_temperature }}) and room {{ temperature_sensor }} has temperature {{ actual_temperature }} (with diff: {{ calculated_adjustment }}). Target temperature diff is {{ calculated_target_temperature_diff }}
    level: info
    logger: blueprints.reshetylo.target_temperature_adjustment_fahrenheit
- service: system_log.write
  data:
    message: >
      thermostat: {{ thermostat }},
      temperature_sensor: {{ temperature_sensor }},
      target_temperature: {{ target_temperature }},
      actual_temperature: {{ actual_temperature }},
      calculated_adjustment: {{ calculated_adjustment }},
      calculated_target_temperature_diff: {{ calculated_target_temperature_diff }}
    level: debug
    logger: blueprints.reshetylo.target_temperature_adjustment_fahrenheit
- service: climate.set_temperature
  data:
    entity_id: "{{ thermostat }}"
    temperature: >
      {% if calculated_target_temperature_diff < 0 %}
      {{ activate_temp }}
      {% else %}
      {{ deactivate_temp }}
      {% endif %}
mode: single
